### ISSUE TITLE
The bug caused by torch version

### ISSUE THREAD

**Issue by unparalleled-ysj** [espnet/espnet_onnx#47] opened 2022-09-20 07:52 UTC
@Masao-Someki Hi Masao, I found a bug, when I use the 1.11.0 version of torch to export the vits model, everything works fine, but when I upgrade the torch version to 1.12.1 (required by torchaudio), I get a core dump when exporting the vits.
Can you reproduce this bug ?   BTW,  everything works fine when export jets model using torch version 1.12.1

Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Floating point exception(core dump)

**Comment by Masao-Someki** [comment] 2022-09-24 04:15
Thank you @unparalleled-ysj,
I tested with torch==1.12 and I could reproduce this bug.
I found that only the VITS model cause this bug, and other models would work well.
It seems that there are some differences in onnx exportation between 1.11 and 1.12, so maybe it is the reason for this bug.
We will check deeper into the version problem..

**Comment by Masao-Someki** [comment] 2022-11-10 07:07
Hi @unparalleled-ysj , 
Could you try this exportation with torch==1.13?
I tried to find the bug in espnet_onnx, but it seems that this issue is caused by the export function `torch.onnx.export` .
I confirmed that this issue is fixed in torch==1.13

**Closed** 2022-11-16 03:56 UTC
